### ISSUE TITLE
Installed binary doesn't work on CentOS 7

### ISSUE THREAD

**Issue by tueda** [ClementTsang/homebrew-bottom#11]
Although I can easily run `cargo install bottom` as a workaround, let me file this issue.

On Linux, the current `bottom` formula copies the binary from https://github.com/ClementTsang/bottom/releases/download/0.4.7/bottom_x86_64-unknown-linux-gnu.tar.gz.
Unfortunately, this binary doesn't work on CentOS 7 (and probably on other old Linux OSes) due to the glibc version mismatch:
```
btm: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by btm)
```

**Comment by ClementTsang** [comment]
Hmm... I'll look into that in a bit.

**Comment by ClementTsang** [comment]
@tueda I've switched to distributing the musl binary instead starting from 0.5.4, which shouldn't have the glibc mismatch issue - could you tell me if this works for you?

**Comment by tueda** [comment]
Thank you for the fix. bottom 0.5.4 installed via Linuxbrew works well in my environment, CentOS 7, without any glibc version error.
